services:
  app:
    image: yogita/springdb:latest
    # Use the Spring Boot app image built from Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/book_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db


  db:
    image: mysql:8.0        # Use MySQL 8.0 image
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root



